services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: peppe:nginx
    volumes:
      - ./project/:/var/www/html/
      - ./docker/nginx/config/:/etc/nginx/conf.d/
      - ./docker/logs/nginx:/var/log/nginx/
    ports:
      - "1337:80"
  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: peppe:php
    volumes:
      - ./project/:/var/www/html/
      - ./docker/logs/php.log:/var/log/fpm-php.www.log
    ports:
      - "1338:9000"
  db:
    container_name: ${PROJECT_NAME}_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '1339:3306'
    expose:
      - '1339'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
